/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentGroups;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shero
 */
public class ManageStudentGroup extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentGroup
     */
    public ManageStudentGroup() {
        initComponents();
        table_update();
         
    }
    
    private void Clear(){
         txtcmbyrseme.setSelectedIndex(0);
         txtcmbprog.setSelectedIndex(0);
         jSpinnergno.setValue(0);
         jSpinnersubgno.setValue(0);
         txtgid.setText("");
         txtsgid.setText("");      
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcmbyrseme = new javax.swing.JComboBox<>();
        jSpinnergno = new javax.swing.JSpinner();
        txtgid = new javax.swing.JTextField();
        txtcmbprog = new javax.swing.JComboBox<>();
        jSpinnersubgno = new javax.swing.JSpinner();
        txtsgid = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtable_stugrp = new javax.swing.JTable();
        btndelstugrp1 = new javax.swing.JButton();
        btnupdtstugrp1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnmenusg1 = new javax.swing.JButton();
        btnclear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 191, 179));

        jLabel2.setText("Academic Year Semester");

        jLabel3.setText("Group Number");

        jLabel4.setText("Group ID");

        jLabel5.setText("Programme");

        jLabel6.setText("Sub Group Number");

        jLabel7.setText("Sub Group ID");

        txtcmbyrseme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y1S1", "Y1S2", "Y2S1", "Y2S2", "Y3S1", "Y3S2", "Y4S1", "Y4S2" }));

        txtcmbprog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "CSE", "IM", "CSNE", "ISE", "DS", "SE" }));

        jtable_stugrp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Academic Year", "Programme", "Group No", "Group ID", "Sub Group No", "Sub Group ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtable_stugrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_stugrpMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtable_stugrp);

        btndelstugrp1.setBackground(new java.awt.Color(0, 153, 153));
        btndelstugrp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelstugrp1.setText("DELETE");
        btndelstugrp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelstugrp1ActionPerformed(evt);
            }
        });

        btnupdtstugrp1.setBackground(new java.awt.Color(0, 153, 153));
        btnupdtstugrp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdtstugrp1.setText("UPDATE");
        btnupdtstugrp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdtstugrp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgid, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnergno, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcmbyrseme, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsgid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnersubgno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcmbprog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnupdtstugrp1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(btndelstugrp1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcmbprog, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsgid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnersubgno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcmbyrseme, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtgid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnergno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdtstugrp1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelstugrp1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE STUDENT GROUPS");

        btnmenusg1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmenusg1.setText("MENU");
        btnmenusg1.setToolTipText("");
        btnmenusg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenusg1ActionPerformed(evt);
            }
        });

        btnclear1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear1.setText("CLEAR");
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnmenusg1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmenusg1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con;
        PreparedStatement insert;
        PreparedStatement upd;
        
         private void table_update(){
          
            int c;
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/timetablemanagement","root","");
            insert = con.prepareStatement("select * from student_group");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel)jtable_stugrp.getModel();
            Df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("sg_id"));
                    v2.add(rs.getString("yearseme"));
                    v2.add(rs.getString("programme"));
                    v2.add(rs.getString("groupno"));
                    v2.add(rs.getString("groupid"));
                    v2.add(rs.getString("subgrpno"));
                    
                    v2.add(rs.getString("subgrpid")); 
                }
                Df.addRow(v2);
                
            }
             
        }
            catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentGroup.class.getName()).log(Level.SEVERE, null, ex);
        }
            
         }
    private void btnmenusg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenusg1ActionPerformed
        // TODO add your handling code here:
        new StudentGroups.StugrpMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmenusg1ActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnclear1ActionPerformed

    private void jtable_stugrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_stugrpMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jtable_stugrp.getModel();
        int selectedIndex = jtable_stugrp.getSelectedRow();

        txtcmbyrseme.setSelectedItem(Df.getValueAt(selectedIndex,1));
        txtcmbyrseme.setSelectedItem(Df.getValueAt(selectedIndex,1));
        txtcmbprog.setSelectedItem(Df.getValueAt(selectedIndex, 2));
        jSpinnergno.setValue(Integer.parseInt(Df.getValueAt(selectedIndex, 3).toString()));
        txtgid.setText(Df.getValueAt(selectedIndex,4).toString());
        jSpinnersubgno.setValue(Integer.parseInt(Df.getValueAt(selectedIndex, 5).toString()));

        txtsgid.setText(Df.getValueAt(selectedIndex,6).toString());
    }//GEN-LAST:event_jtable_stugrpMouseClicked

    private void btndelstugrp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelstugrp1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jtable_stugrp.getModel();
        int selectedIndex = jtable_stugrp.getSelectedRow();

        try {

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete","Warning",JOptionPane.YES_NO_OPTION);

            if(dialogResult ==  JOptionPane.YES_OPTION )
            {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/timetablemanagement","root","");

                insert = con.prepareStatement("delete from student_group where sg_id = ?  ");

                insert.setString(1,Df.getValueAt(selectedIndex, 0).toString());

                insert.executeUpdate();
                JOptionPane.showMessageDialog(this,"Record Deleted");
                table_update();

                txtcmbyrseme.setSelectedItem("");
                txtcmbprog.setSelectedItem("");
                jSpinnergno.setValue(0);
                jSpinnersubgno.setValue(0);
                txtgid.setText("");
                txtsgid.setText("");
                txtsgid.requestFocus();
            }
        }

        catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageStudentGroup.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(ManageStudentGroup.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btndelstugrp1ActionPerformed

    private void btnupdtstugrp1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jtable_stugrp.getModel();
        int selectedIndex = jtable_stugrp.getSelectedRow();

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/timetablemanagement","root","");
            upd = con.prepareStatement("update student_group  set yearseme= ?,programme= ?,groupno= ?,subgrpno= ?,groupid= ?,subgrpid= ? where sg_id= ?");

            String yearseme = txtcmbyrseme.getSelectedItem().toString();
            String programme = txtcmbprog.getSelectedItem().toString();
            String groupno = jSpinnergno.getValue().toString();
            String subgrpno = jSpinnersubgno.getValue().toString();
            String groupid = txtgid.getText();
            String subgrpid = txtsgid.getText();

            upd.setString(1, yearseme);
            upd.setString(2, programme );
            upd.setString(3, groupno);
            upd.setString(4, subgrpno);
            upd.setString(5, yearseme+"."+programme+"."+groupno);
            upd.setString(6, yearseme+"."+programme+"."+groupno+"."+subgrpno);
            upd.setString(7,Df.getValueAt(selectedIndex, 0).toString());

            if(yearseme.isEmpty() || programme.isEmpty() || groupno.isEmpty() || subgrpno.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please fill required details!");
            }
            else{
                upd.executeUpdate();
                JOptionPane.showMessageDialog(this,"Record updated");
                table_update();

                txtcmbyrseme.setSelectedItem("");
                txtcmbprog.setSelectedItem("");
                txtgid.setText("");
                txtsgid.setText("");
                txtgid.requestFocus();
                txtsgid.requestFocus();
            }

        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentGroup.class.getName()).log(Level.SEVERE, null, ex);
        }
        }                                      

        private void txtsgidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsgidActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_txtsgidActionPerformed

        private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {                                         
            // TODO add your handling code here:

            Clear();
    
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btndelstugrp1;
    private javax.swing.JButton btnmenusg1;
    private javax.swing.JButton btnupdtstugrp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnergno;
    private javax.swing.JSpinner jSpinnersubgno;
    private javax.swing.JTable jtable_stugrp;
    private javax.swing.JComboBox<String> txtcmbprog;
    private javax.swing.JComboBox<String> txtcmbyrseme;
    private javax.swing.JTextField txtgid;
    private javax.swing.JTextField txtsgid;
    // End of variables declaration//GEN-END:variables
}
